export const colors = {
  blue: '#1D4354',
  white: '#fff',
  grey: '#d3d3d3',
  green: '#61DEA4',
  red: '#F45E6D',
};

export const actions = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  GET_USERS: 'GET_USERS',
  USERS_RECEIVED: 'USERS_RECEIVED',
  ADD_USER: 'ADD_USER',

  GET_POLLS: 'GET_POLLS',
  POLLS_RECEIVED: 'POLLS_RECEIVED',

  CREATE_POLL: 'CREATE_POLL',
  EDIT_POLL: 'EDIT_POLL',
  DELETE_POLL: 'DELETE_POLL',

  CREATE_OPTION: 'CREATE_OPTION',
  DELETE_OPTION: 'DELETE_OPTION',
};
